// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/environment/reset_requests/ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/environment/reset_requests/ports.go -destination=internal/app/environment/reset_requests/mock/ports.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entities "github.com/MAD-py/pandora-core/internal/domain/entities"
	errors "github.com/MAD-py/pandora-core/internal/domain/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockEnvironmentRepository is a mock of EnvironmentRepository interface.
type MockEnvironmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEnvironmentRepositoryMockRecorder
	isgomock struct{}
}

// MockEnvironmentRepositoryMockRecorder is the mock recorder for MockEnvironmentRepository.
type MockEnvironmentRepositoryMockRecorder struct {
	mock *MockEnvironmentRepository
}

// NewMockEnvironmentRepository creates a new mock instance.
func NewMockEnvironmentRepository(ctrl *gomock.Controller) *MockEnvironmentRepository {
	mock := &MockEnvironmentRepository{ctrl: ctrl}
	mock.recorder = &MockEnvironmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvironmentRepository) EXPECT() *MockEnvironmentRepositoryMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockEnvironmentRepository) Exists(ctx context.Context, id int) (bool, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockEnvironmentRepositoryMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockEnvironmentRepository)(nil).Exists), ctx, id)
}

// ResetAvailableRequests mocks base method.
func (m *MockEnvironmentRepository) ResetAvailableRequests(ctx context.Context, id, serviceID int) (*entities.EnvironmentService, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetAvailableRequests", ctx, id, serviceID)
	ret0, _ := ret[0].(*entities.EnvironmentService)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// ResetAvailableRequests indicates an expected call of ResetAvailableRequests.
func (mr *MockEnvironmentRepositoryMockRecorder) ResetAvailableRequests(ctx, id, serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetAvailableRequests", reflect.TypeOf((*MockEnvironmentRepository)(nil).ResetAvailableRequests), ctx, id, serviceID)
}
