// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api_key/v1/api_key.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseValidateParams struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Service        string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Environment    string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	ServiceVersion string                 `protobuf:"bytes,4,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	RequestTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BaseValidateParams) Reset() {
	*x = BaseValidateParams{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseValidateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseValidateParams) ProtoMessage() {}

func (x *BaseValidateParams) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseValidateParams.ProtoReflect.Descriptor instead.
func (*BaseValidateParams) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{0}
}

func (x *BaseValidateParams) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BaseValidateParams) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *BaseValidateParams) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *BaseValidateParams) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *BaseValidateParams) GetRequestTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestTime
	}
	return nil
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *BaseValidateParams    `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateRequest) GetParams() *BaseValidateParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type ValidateAndConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *BaseValidateParams    `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAndConsumeRequest) Reset() {
	*x = ValidateAndConsumeRequest{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAndConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAndConsumeRequest) ProtoMessage() {}

func (x *ValidateAndConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAndConsumeRequest.ProtoReflect.Descriptor instead.
func (*ValidateAndConsumeRequest) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateAndConsumeRequest) GetParams() *BaseValidateParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type ValidateAndReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAndReservationRequest) Reset() {
	*x = ValidateAndReservationRequest{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAndReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAndReservationRequest) ProtoMessage() {}

func (x *ValidateAndReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAndReservationRequest.ProtoReflect.Descriptor instead.
func (*ValidateAndReservationRequest) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateAndReservationRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ValidateAndReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ValidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Valid bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*ValidateResponse_Successful_
	//	*ValidateResponse_Failed_
	Result        isValidateResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetResult() isValidateResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ValidateResponse) GetSuccessful() *ValidateResponse_Successful {
	if x != nil {
		if x, ok := x.Result.(*ValidateResponse_Successful_); ok {
			return x.Successful
		}
	}
	return nil
}

func (x *ValidateResponse) GetFailed() *ValidateResponse_Failed {
	if x != nil {
		if x, ok := x.Result.(*ValidateResponse_Failed_); ok {
			return x.Failed
		}
	}
	return nil
}

type isValidateResponse_Result interface {
	isValidateResponse_Result()
}

type ValidateResponse_Successful_ struct {
	Successful *ValidateResponse_Successful `protobuf:"bytes,2,opt,name=successful,proto3,oneof"`
}

type ValidateResponse_Failed_ struct {
	Failed *ValidateResponse_Failed `protobuf:"bytes,3,opt,name=failed,proto3,oneof"`
}

func (*ValidateResponse_Successful_) isValidateResponse_Result() {}

func (*ValidateResponse_Failed_) isValidateResponse_Result() {}

type ValidateAndConsumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Valid bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*ValidateAndConsumeResponse_Successful_
	//	*ValidateAndConsumeResponse_Failed_
	Result        isValidateAndConsumeResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAndConsumeResponse) Reset() {
	*x = ValidateAndConsumeResponse{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAndConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAndConsumeResponse) ProtoMessage() {}

func (x *ValidateAndConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAndConsumeResponse.ProtoReflect.Descriptor instead.
func (*ValidateAndConsumeResponse) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateAndConsumeResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateAndConsumeResponse) GetResult() isValidateAndConsumeResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ValidateAndConsumeResponse) GetSuccessful() *ValidateAndConsumeResponse_Successful {
	if x != nil {
		if x, ok := x.Result.(*ValidateAndConsumeResponse_Successful_); ok {
			return x.Successful
		}
	}
	return nil
}

func (x *ValidateAndConsumeResponse) GetFailed() *ValidateAndConsumeResponse_Failed {
	if x != nil {
		if x, ok := x.Result.(*ValidateAndConsumeResponse_Failed_); ok {
			return x.Failed
		}
	}
	return nil
}

type isValidateAndConsumeResponse_Result interface {
	isValidateAndConsumeResponse_Result()
}

type ValidateAndConsumeResponse_Successful_ struct {
	Successful *ValidateAndConsumeResponse_Successful `protobuf:"bytes,2,opt,name=successful,proto3,oneof"`
}

type ValidateAndConsumeResponse_Failed_ struct {
	Failed *ValidateAndConsumeResponse_Failed `protobuf:"bytes,3,opt,name=failed,proto3,oneof"`
}

func (*ValidateAndConsumeResponse_Successful_) isValidateAndConsumeResponse_Result() {}

func (*ValidateAndConsumeResponse_Failed_) isValidateAndConsumeResponse_Result() {}

type ValidateAndReservationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Valid bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*ValidateAndReservationResponse_Successful_
	//	*ValidateAndReservationResponse_Failed_
	Result        isValidateAndReservationResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAndReservationResponse) Reset() {
	*x = ValidateAndReservationResponse{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAndReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAndReservationResponse) ProtoMessage() {}

func (x *ValidateAndReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAndReservationResponse.ProtoReflect.Descriptor instead.
func (*ValidateAndReservationResponse) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateAndReservationResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateAndReservationResponse) GetResult() isValidateAndReservationResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ValidateAndReservationResponse) GetSuccessful() *ValidateAndReservationResponse_Successful {
	if x != nil {
		if x, ok := x.Result.(*ValidateAndReservationResponse_Successful_); ok {
			return x.Successful
		}
	}
	return nil
}

func (x *ValidateAndReservationResponse) GetFailed() *ValidateAndReservationResponse_Failed {
	if x != nil {
		if x, ok := x.Result.(*ValidateAndReservationResponse_Failed_); ok {
			return x.Failed
		}
	}
	return nil
}

type isValidateAndReservationResponse_Result interface {
	isValidateAndReservationResponse_Result()
}

type ValidateAndReservationResponse_Successful_ struct {
	Successful *ValidateAndReservationResponse_Successful `protobuf:"bytes,2,opt,name=successful,proto3,oneof"`
}

type ValidateAndReservationResponse_Failed_ struct {
	Failed *ValidateAndReservationResponse_Failed `protobuf:"bytes,3,opt,name=failed,proto3,oneof"`
}

func (*ValidateAndReservationResponse_Successful_) isValidateAndReservationResponse_Result() {}

func (*ValidateAndReservationResponse_Failed_) isValidateAndReservationResponse_Result() {}

type ValidateResponse_Successful struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse_Successful) Reset() {
	*x = ValidateResponse_Successful{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse_Successful) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse_Successful) ProtoMessage() {}

func (x *ValidateResponse_Successful) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse_Successful.ProtoReflect.Descriptor instead.
func (*ValidateResponse_Successful) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ValidateResponse_Successful) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ValidateResponse_Failed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse_Failed) Reset() {
	*x = ValidateResponse_Failed{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse_Failed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse_Failed) ProtoMessage() {}

func (x *ValidateResponse_Failed) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse_Failed.ProtoReflect.Descriptor instead.
func (*ValidateResponse_Failed) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ValidateResponse_Failed) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ValidateResponse_Failed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateAndConsumeResponse_Successful struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AvailableRequest int64                  `protobuf:"varint,2,opt,name=available_request,json=availableRequest,proto3" json:"available_request,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateAndConsumeResponse_Successful) Reset() {
	*x = ValidateAndConsumeResponse_Successful{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAndConsumeResponse_Successful) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAndConsumeResponse_Successful) ProtoMessage() {}

func (x *ValidateAndConsumeResponse_Successful) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAndConsumeResponse_Successful.ProtoReflect.Descriptor instead.
func (*ValidateAndConsumeResponse_Successful) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ValidateAndConsumeResponse_Successful) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ValidateAndConsumeResponse_Successful) GetAvailableRequest() int64 {
	if x != nil {
		return x.AvailableRequest
	}
	return 0
}

type ValidateAndConsumeResponse_Failed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAndConsumeResponse_Failed) Reset() {
	*x = ValidateAndConsumeResponse_Failed{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAndConsumeResponse_Failed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAndConsumeResponse_Failed) ProtoMessage() {}

func (x *ValidateAndConsumeResponse_Failed) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAndConsumeResponse_Failed.ProtoReflect.Descriptor instead.
func (*ValidateAndConsumeResponse_Failed) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{5, 1}
}

func (x *ValidateAndConsumeResponse_Failed) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ValidateAndConsumeResponse_Failed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateAndReservationResponse_Successful struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AvailableRequest int64                  `protobuf:"varint,2,opt,name=available_request,json=availableRequest,proto3" json:"available_request,omitempty"`
	ReservationId    string                 `protobuf:"bytes,3,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateAndReservationResponse_Successful) Reset() {
	*x = ValidateAndReservationResponse_Successful{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAndReservationResponse_Successful) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAndReservationResponse_Successful) ProtoMessage() {}

func (x *ValidateAndReservationResponse_Successful) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAndReservationResponse_Successful.ProtoReflect.Descriptor instead.
func (*ValidateAndReservationResponse_Successful) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ValidateAndReservationResponse_Successful) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ValidateAndReservationResponse_Successful) GetAvailableRequest() int64 {
	if x != nil {
		return x.AvailableRequest
	}
	return 0
}

func (x *ValidateAndReservationResponse_Successful) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ValidateAndReservationResponse_Failed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAndReservationResponse_Failed) Reset() {
	*x = ValidateAndReservationResponse_Failed{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAndReservationResponse_Failed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAndReservationResponse_Failed) ProtoMessage() {}

func (x *ValidateAndReservationResponse_Failed) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAndReservationResponse_Failed.ProtoReflect.Descriptor instead.
func (*ValidateAndReservationResponse_Failed) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{6, 1}
}

func (x *ValidateAndReservationResponse_Failed) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ValidateAndReservationResponse_Failed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_key_v1_api_key_proto protoreflect.FileDescriptor

const file_api_key_v1_api_key_proto_rawDesc = "" +
	"\n" +
	"\x18api_key/v1/api_key.proto\x12\n" +
	"api_key.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x01\n" +
	"\x12BaseValidateParams\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12'\n" +
	"\x0fservice_version\x18\x04 \x01(\tR\x0eserviceVersion\x12=\n" +
	"\frequest_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestTime\"I\n" +
	"\x0fValidateRequest\x126\n" +
	"\x06params\x18\x01 \x01(\v2\x1e.api_key.v1.BaseValidateParamsR\x06params\"S\n" +
	"\x19ValidateAndConsumeRequest\x126\n" +
	"\x06params\x18\x01 \x01(\v2\x1e.api_key.v1.BaseValidateParamsR\x06params\"X\n" +
	"\x1dValidateAndReservationRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\"\xa1\x02\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12I\n" +
	"\n" +
	"successful\x18\x02 \x01(\v2'.api_key.v1.ValidateResponse.SuccessfulH\x00R\n" +
	"successful\x12=\n" +
	"\x06failed\x18\x03 \x01(\v2#.api_key.v1.ValidateResponse.FailedH\x00R\x06failed\x1a+\n" +
	"\n" +
	"Successful\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x1a6\n" +
	"\x06Failed\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\b\n" +
	"\x06result\"\xec\x02\n" +
	"\x1aValidateAndConsumeResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12S\n" +
	"\n" +
	"successful\x18\x02 \x01(\v21.api_key.v1.ValidateAndConsumeResponse.SuccessfulH\x00R\n" +
	"successful\x12G\n" +
	"\x06failed\x18\x03 \x01(\v2-.api_key.v1.ValidateAndConsumeResponse.FailedH\x00R\x06failed\x1aX\n" +
	"\n" +
	"Successful\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\x11available_request\x18\x02 \x01(\x03R\x10availableRequest\x1a6\n" +
	"\x06Failed\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\b\n" +
	"\x06result\"\x9f\x03\n" +
	"\x1eValidateAndReservationResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12W\n" +
	"\n" +
	"successful\x18\x02 \x01(\v25.api_key.v1.ValidateAndReservationResponse.SuccessfulH\x00R\n" +
	"successful\x12K\n" +
	"\x06failed\x18\x03 \x01(\v21.api_key.v1.ValidateAndReservationResponse.FailedH\x00R\x06failed\x1a\x7f\n" +
	"\n" +
	"Successful\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\x11available_request\x18\x02 \x01(\x03R\x10availableRequest\x12%\n" +
	"\x0ereservation_id\x18\x03 \x01(\tR\rreservationId\x1a6\n" +
	"\x06Failed\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\b\n" +
	"\x06result2\xac\x02\n" +
	"\rAPIKeyService\x12E\n" +
	"\bValidate\x12\x1b.api_key.v1.ValidateRequest\x1a\x1c.api_key.v1.ValidateResponse\x12c\n" +
	"\x12ValidateAndConsume\x12%.api_key.v1.ValidateAndConsumeRequest\x1a&.api_key.v1.ValidateAndConsumeResponse\x12o\n" +
	"\x16ValidateAndReservation\x12).api_key.v1.ValidateAndReservationRequest\x1a*.api_key.v1.ValidateAndReservationResponseB\fZ\n" +
	"api_key/pbb\x06proto3"

var (
	file_api_key_v1_api_key_proto_rawDescOnce sync.Once
	file_api_key_v1_api_key_proto_rawDescData []byte
)

func file_api_key_v1_api_key_proto_rawDescGZIP() []byte {
	file_api_key_v1_api_key_proto_rawDescOnce.Do(func() {
		file_api_key_v1_api_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_key_v1_api_key_proto_rawDesc), len(file_api_key_v1_api_key_proto_rawDesc)))
	})
	return file_api_key_v1_api_key_proto_rawDescData
}

var file_api_key_v1_api_key_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_key_v1_api_key_proto_goTypes = []any{
	(*BaseValidateParams)(nil),                        // 0: api_key.v1.BaseValidateParams
	(*ValidateRequest)(nil),                           // 1: api_key.v1.ValidateRequest
	(*ValidateAndConsumeRequest)(nil),                 // 2: api_key.v1.ValidateAndConsumeRequest
	(*ValidateAndReservationRequest)(nil),             // 3: api_key.v1.ValidateAndReservationRequest
	(*ValidateResponse)(nil),                          // 4: api_key.v1.ValidateResponse
	(*ValidateAndConsumeResponse)(nil),                // 5: api_key.v1.ValidateAndConsumeResponse
	(*ValidateAndReservationResponse)(nil),            // 6: api_key.v1.ValidateAndReservationResponse
	(*ValidateResponse_Successful)(nil),               // 7: api_key.v1.ValidateResponse.Successful
	(*ValidateResponse_Failed)(nil),                   // 8: api_key.v1.ValidateResponse.Failed
	(*ValidateAndConsumeResponse_Successful)(nil),     // 9: api_key.v1.ValidateAndConsumeResponse.Successful
	(*ValidateAndConsumeResponse_Failed)(nil),         // 10: api_key.v1.ValidateAndConsumeResponse.Failed
	(*ValidateAndReservationResponse_Successful)(nil), // 11: api_key.v1.ValidateAndReservationResponse.Successful
	(*ValidateAndReservationResponse_Failed)(nil),     // 12: api_key.v1.ValidateAndReservationResponse.Failed
	(*timestamppb.Timestamp)(nil),                     // 13: google.protobuf.Timestamp
}
var file_api_key_v1_api_key_proto_depIdxs = []int32{
	13, // 0: api_key.v1.BaseValidateParams.request_time:type_name -> google.protobuf.Timestamp
	0,  // 1: api_key.v1.ValidateRequest.params:type_name -> api_key.v1.BaseValidateParams
	0,  // 2: api_key.v1.ValidateAndConsumeRequest.params:type_name -> api_key.v1.BaseValidateParams
	7,  // 3: api_key.v1.ValidateResponse.successful:type_name -> api_key.v1.ValidateResponse.Successful
	8,  // 4: api_key.v1.ValidateResponse.failed:type_name -> api_key.v1.ValidateResponse.Failed
	9,  // 5: api_key.v1.ValidateAndConsumeResponse.successful:type_name -> api_key.v1.ValidateAndConsumeResponse.Successful
	10, // 6: api_key.v1.ValidateAndConsumeResponse.failed:type_name -> api_key.v1.ValidateAndConsumeResponse.Failed
	11, // 7: api_key.v1.ValidateAndReservationResponse.successful:type_name -> api_key.v1.ValidateAndReservationResponse.Successful
	12, // 8: api_key.v1.ValidateAndReservationResponse.failed:type_name -> api_key.v1.ValidateAndReservationResponse.Failed
	1,  // 9: api_key.v1.APIKeyService.Validate:input_type -> api_key.v1.ValidateRequest
	2,  // 10: api_key.v1.APIKeyService.ValidateAndConsume:input_type -> api_key.v1.ValidateAndConsumeRequest
	3,  // 11: api_key.v1.APIKeyService.ValidateAndReservation:input_type -> api_key.v1.ValidateAndReservationRequest
	4,  // 12: api_key.v1.APIKeyService.Validate:output_type -> api_key.v1.ValidateResponse
	5,  // 13: api_key.v1.APIKeyService.ValidateAndConsume:output_type -> api_key.v1.ValidateAndConsumeResponse
	6,  // 14: api_key.v1.APIKeyService.ValidateAndReservation:output_type -> api_key.v1.ValidateAndReservationResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_key_v1_api_key_proto_init() }
func file_api_key_v1_api_key_proto_init() {
	if File_api_key_v1_api_key_proto != nil {
		return
	}
	file_api_key_v1_api_key_proto_msgTypes[4].OneofWrappers = []any{
		(*ValidateResponse_Successful_)(nil),
		(*ValidateResponse_Failed_)(nil),
	}
	file_api_key_v1_api_key_proto_msgTypes[5].OneofWrappers = []any{
		(*ValidateAndConsumeResponse_Successful_)(nil),
		(*ValidateAndConsumeResponse_Failed_)(nil),
	}
	file_api_key_v1_api_key_proto_msgTypes[6].OneofWrappers = []any{
		(*ValidateAndReservationResponse_Successful_)(nil),
		(*ValidateAndReservationResponse_Failed_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_key_v1_api_key_proto_rawDesc), len(file_api_key_v1_api_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_key_v1_api_key_proto_goTypes,
		DependencyIndexes: file_api_key_v1_api_key_proto_depIdxs,
		MessageInfos:      file_api_key_v1_api_key_proto_msgTypes,
	}.Build()
	File_api_key_v1_api_key_proto = out.File
	file_api_key_v1_api_key_proto_goTypes = nil
	file_api_key_v1_api_key_proto_depIdxs = nil
}
