// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: internal/adapters/grpc/api_key/proto/api_key.proto

package pb

import (
	timestamp "google.golang.org/protobuf/types/known/timestamppb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIKeyValidate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Service        string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Environment    string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	ServiceVersion string                 `protobuf:"bytes,4,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	RequestTime    *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *APIKeyValidate) Reset() {
	*x = APIKeyValidate{}
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyValidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyValidate) ProtoMessage() {}

func (x *APIKeyValidate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyValidate.ProtoReflect.Descriptor instead.
func (*APIKeyValidate) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescGZIP(), []int{0}
}

func (x *APIKeyValidate) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *APIKeyValidate) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *APIKeyValidate) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *APIKeyValidate) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *APIKeyValidate) GetRequestTime() *timestamp.Timestamp {
	if x != nil {
		return x.RequestTime
	}
	return nil
}

type APIKeyValidateBooking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	BookingId     string                 `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyValidateBooking) Reset() {
	*x = APIKeyValidateBooking{}
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyValidateBooking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyValidateBooking) ProtoMessage() {}

func (x *APIKeyValidateBooking) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyValidateBooking.ProtoReflect.Descriptor instead.
func (*APIKeyValidateBooking) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescGZIP(), []int{1}
}

func (x *APIKeyValidateBooking) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *APIKeyValidateBooking) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type APIKeyValidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Valid bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*APIKeyValidateResponse_Successful_
	//	*APIKeyValidateResponse_Failed_
	Result        isAPIKeyValidateResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyValidateResponse) Reset() {
	*x = APIKeyValidateResponse{}
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyValidateResponse) ProtoMessage() {}

func (x *APIKeyValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyValidateResponse.ProtoReflect.Descriptor instead.
func (*APIKeyValidateResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescGZIP(), []int{2}
}

func (x *APIKeyValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *APIKeyValidateResponse) GetResult() isAPIKeyValidateResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *APIKeyValidateResponse) GetSuccessful() *APIKeyValidateResponse_Successful {
	if x != nil {
		if x, ok := x.Result.(*APIKeyValidateResponse_Successful_); ok {
			return x.Successful
		}
	}
	return nil
}

func (x *APIKeyValidateResponse) GetFailed() *APIKeyValidateResponse_Failed {
	if x != nil {
		if x, ok := x.Result.(*APIKeyValidateResponse_Failed_); ok {
			return x.Failed
		}
	}
	return nil
}

type isAPIKeyValidateResponse_Result interface {
	isAPIKeyValidateResponse_Result()
}

type APIKeyValidateResponse_Successful_ struct {
	Successful *APIKeyValidateResponse_Successful `protobuf:"bytes,2,opt,name=successful,proto3,oneof"`
}

type APIKeyValidateResponse_Failed_ struct {
	Failed *APIKeyValidateResponse_Failed `protobuf:"bytes,3,opt,name=failed,proto3,oneof"`
}

func (*APIKeyValidateResponse_Successful_) isAPIKeyValidateResponse_Result() {}

func (*APIKeyValidateResponse_Failed_) isAPIKeyValidateResponse_Result() {}

type APIKeyValidateConsumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Valid bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*APIKeyValidateConsumeResponse_Successful_
	//	*APIKeyValidateConsumeResponse_Failed_
	Result        isAPIKeyValidateConsumeResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyValidateConsumeResponse) Reset() {
	*x = APIKeyValidateConsumeResponse{}
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyValidateConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyValidateConsumeResponse) ProtoMessage() {}

func (x *APIKeyValidateConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyValidateConsumeResponse.ProtoReflect.Descriptor instead.
func (*APIKeyValidateConsumeResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescGZIP(), []int{3}
}

func (x *APIKeyValidateConsumeResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *APIKeyValidateConsumeResponse) GetResult() isAPIKeyValidateConsumeResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *APIKeyValidateConsumeResponse) GetSuccessful() *APIKeyValidateConsumeResponse_Successful {
	if x != nil {
		if x, ok := x.Result.(*APIKeyValidateConsumeResponse_Successful_); ok {
			return x.Successful
		}
	}
	return nil
}

func (x *APIKeyValidateConsumeResponse) GetFailed() *APIKeyValidateConsumeResponse_Failed {
	if x != nil {
		if x, ok := x.Result.(*APIKeyValidateConsumeResponse_Failed_); ok {
			return x.Failed
		}
	}
	return nil
}

type isAPIKeyValidateConsumeResponse_Result interface {
	isAPIKeyValidateConsumeResponse_Result()
}

type APIKeyValidateConsumeResponse_Successful_ struct {
	Successful *APIKeyValidateConsumeResponse_Successful `protobuf:"bytes,2,opt,name=successful,proto3,oneof"`
}

type APIKeyValidateConsumeResponse_Failed_ struct {
	Failed *APIKeyValidateConsumeResponse_Failed `protobuf:"bytes,3,opt,name=failed,proto3,oneof"`
}

func (*APIKeyValidateConsumeResponse_Successful_) isAPIKeyValidateConsumeResponse_Result() {}

func (*APIKeyValidateConsumeResponse_Failed_) isAPIKeyValidateConsumeResponse_Result() {}

type APIKeyValidateBookingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Valid bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*APIKeyValidateBookingResponse_Successful_
	//	*APIKeyValidateBookingResponse_Failed_
	Result        isAPIKeyValidateBookingResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyValidateBookingResponse) Reset() {
	*x = APIKeyValidateBookingResponse{}
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyValidateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyValidateBookingResponse) ProtoMessage() {}

func (x *APIKeyValidateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyValidateBookingResponse.ProtoReflect.Descriptor instead.
func (*APIKeyValidateBookingResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescGZIP(), []int{4}
}

func (x *APIKeyValidateBookingResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *APIKeyValidateBookingResponse) GetResult() isAPIKeyValidateBookingResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *APIKeyValidateBookingResponse) GetSuccessful() *APIKeyValidateBookingResponse_Successful {
	if x != nil {
		if x, ok := x.Result.(*APIKeyValidateBookingResponse_Successful_); ok {
			return x.Successful
		}
	}
	return nil
}

func (x *APIKeyValidateBookingResponse) GetFailed() *APIKeyValidateBookingResponse_Failed {
	if x != nil {
		if x, ok := x.Result.(*APIKeyValidateBookingResponse_Failed_); ok {
			return x.Failed
		}
	}
	return nil
}

type isAPIKeyValidateBookingResponse_Result interface {
	isAPIKeyValidateBookingResponse_Result()
}

type APIKeyValidateBookingResponse_Successful_ struct {
	Successful *APIKeyValidateBookingResponse_Successful `protobuf:"bytes,2,opt,name=successful,proto3,oneof"`
}

type APIKeyValidateBookingResponse_Failed_ struct {
	Failed *APIKeyValidateBookingResponse_Failed `protobuf:"bytes,3,opt,name=failed,proto3,oneof"`
}

func (*APIKeyValidateBookingResponse_Successful_) isAPIKeyValidateBookingResponse_Result() {}

func (*APIKeyValidateBookingResponse_Failed_) isAPIKeyValidateBookingResponse_Result() {}

type APIKeyValidateResponse_Successful struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyValidateResponse_Successful) Reset() {
	*x = APIKeyValidateResponse_Successful{}
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyValidateResponse_Successful) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyValidateResponse_Successful) ProtoMessage() {}

func (x *APIKeyValidateResponse_Successful) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyValidateResponse_Successful.ProtoReflect.Descriptor instead.
func (*APIKeyValidateResponse_Successful) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescGZIP(), []int{2, 0}
}

func (x *APIKeyValidateResponse_Successful) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type APIKeyValidateResponse_Failed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyValidateResponse_Failed) Reset() {
	*x = APIKeyValidateResponse_Failed{}
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyValidateResponse_Failed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyValidateResponse_Failed) ProtoMessage() {}

func (x *APIKeyValidateResponse_Failed) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyValidateResponse_Failed.ProtoReflect.Descriptor instead.
func (*APIKeyValidateResponse_Failed) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescGZIP(), []int{2, 1}
}

func (x *APIKeyValidateResponse_Failed) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *APIKeyValidateResponse_Failed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type APIKeyValidateConsumeResponse_Successful struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AvailableRequest int64                  `protobuf:"varint,2,opt,name=available_request,json=availableRequest,proto3" json:"available_request,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *APIKeyValidateConsumeResponse_Successful) Reset() {
	*x = APIKeyValidateConsumeResponse_Successful{}
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyValidateConsumeResponse_Successful) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyValidateConsumeResponse_Successful) ProtoMessage() {}

func (x *APIKeyValidateConsumeResponse_Successful) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyValidateConsumeResponse_Successful.ProtoReflect.Descriptor instead.
func (*APIKeyValidateConsumeResponse_Successful) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescGZIP(), []int{3, 0}
}

func (x *APIKeyValidateConsumeResponse_Successful) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *APIKeyValidateConsumeResponse_Successful) GetAvailableRequest() int64 {
	if x != nil {
		return x.AvailableRequest
	}
	return 0
}

type APIKeyValidateConsumeResponse_Failed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyValidateConsumeResponse_Failed) Reset() {
	*x = APIKeyValidateConsumeResponse_Failed{}
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyValidateConsumeResponse_Failed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyValidateConsumeResponse_Failed) ProtoMessage() {}

func (x *APIKeyValidateConsumeResponse_Failed) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyValidateConsumeResponse_Failed.ProtoReflect.Descriptor instead.
func (*APIKeyValidateConsumeResponse_Failed) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescGZIP(), []int{3, 1}
}

func (x *APIKeyValidateConsumeResponse_Failed) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *APIKeyValidateConsumeResponse_Failed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type APIKeyValidateBookingResponse_Successful struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AvailableRequest int64                  `protobuf:"varint,2,opt,name=available_request,json=availableRequest,proto3" json:"available_request,omitempty"`
	BookingId        string                 `protobuf:"bytes,3,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *APIKeyValidateBookingResponse_Successful) Reset() {
	*x = APIKeyValidateBookingResponse_Successful{}
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyValidateBookingResponse_Successful) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyValidateBookingResponse_Successful) ProtoMessage() {}

func (x *APIKeyValidateBookingResponse_Successful) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyValidateBookingResponse_Successful.ProtoReflect.Descriptor instead.
func (*APIKeyValidateBookingResponse_Successful) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescGZIP(), []int{4, 0}
}

func (x *APIKeyValidateBookingResponse_Successful) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *APIKeyValidateBookingResponse_Successful) GetAvailableRequest() int64 {
	if x != nil {
		return x.AvailableRequest
	}
	return 0
}

func (x *APIKeyValidateBookingResponse_Successful) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type APIKeyValidateBookingResponse_Failed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyValidateBookingResponse_Failed) Reset() {
	*x = APIKeyValidateBookingResponse_Failed{}
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyValidateBookingResponse_Failed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyValidateBookingResponse_Failed) ProtoMessage() {}

func (x *APIKeyValidateBookingResponse_Failed) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyValidateBookingResponse_Failed.ProtoReflect.Descriptor instead.
func (*APIKeyValidateBookingResponse_Failed) Descriptor() ([]byte, []int) {
	return file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescGZIP(), []int{4, 1}
}

func (x *APIKeyValidateBookingResponse_Failed) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *APIKeyValidateBookingResponse_Failed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_adapters_grpc_api_key_proto_api_key_proto protoreflect.FileDescriptor

const file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDesc = "" +
	"\n" +
	"2internal/adapters/grpc/api_key/proto/api_key.proto\x12\aapi_key\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x01\n" +
	"\x0eAPIKeyValidate\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12'\n" +
	"\x0fservice_version\x18\x04 \x01(\tR\x0eserviceVersion\x12=\n" +
	"\frequest_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestTime\"H\n" +
	"\x15APIKeyValidateBooking\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\"\xad\x02\n" +
	"\x16APIKeyValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12L\n" +
	"\n" +
	"successful\x18\x02 \x01(\v2*.api_key.APIKeyValidateResponse.SuccessfulH\x00R\n" +
	"successful\x12@\n" +
	"\x06failed\x18\x03 \x01(\v2&.api_key.APIKeyValidateResponse.FailedH\x00R\x06failed\x1a+\n" +
	"\n" +
	"Successful\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x1a6\n" +
	"\x06Failed\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\b\n" +
	"\x06result\"\xef\x02\n" +
	"\x1dAPIKeyValidateConsumeResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12S\n" +
	"\n" +
	"successful\x18\x02 \x01(\v21.api_key.APIKeyValidateConsumeResponse.SuccessfulH\x00R\n" +
	"successful\x12G\n" +
	"\x06failed\x18\x03 \x01(\v2-.api_key.APIKeyValidateConsumeResponse.FailedH\x00R\x06failed\x1aX\n" +
	"\n" +
	"Successful\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\x11available_request\x18\x02 \x01(\x03R\x10availableRequest\x1a6\n" +
	"\x06Failed\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\b\n" +
	"\x06result\"\x8e\x03\n" +
	"\x1dAPIKeyValidateBookingResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12S\n" +
	"\n" +
	"successful\x18\x02 \x01(\v21.api_key.APIKeyValidateBookingResponse.SuccessfulH\x00R\n" +
	"successful\x12G\n" +
	"\x06failed\x18\x03 \x01(\v2-.api_key.APIKeyValidateBookingResponse.FailedH\x00R\x06failed\x1aw\n" +
	"\n" +
	"Successful\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\x11available_request\x18\x02 \x01(\x03R\x10availableRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x03 \x01(\tR\tbookingId\x1a6\n" +
	"\x06Failed\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\b\n" +
	"\x06result2\x8a\x02\n" +
	"\rAPIKeyService\x12K\n" +
	"\bValidate\x12\x1e.api_key.APIKeyValidateBooking\x1a\x1f.api_key.APIKeyValidateResponse\x12U\n" +
	"\x12ValidateAndConsume\x12\x17.api_key.APIKeyValidate\x1a&.api_key.APIKeyValidateConsumeResponse\x12U\n" +
	"\x12ValidateAndBooking\x12\x17.api_key.APIKeyValidate\x1a&.api_key.APIKeyValidateBookingResponseB#Z!internal/adapters/grpc/api_key/pbb\x06proto3"

var (
	file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescOnce sync.Once
	file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescData []byte
)

func file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescGZIP() []byte {
	file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescOnce.Do(func() {
		file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDesc), len(file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDesc)))
	})
	return file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDescData
}

var file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_adapters_grpc_api_key_proto_api_key_proto_goTypes = []any{
	(*APIKeyValidate)(nil),                           // 0: api_key.APIKeyValidate
	(*APIKeyValidateBooking)(nil),                    // 1: api_key.APIKeyValidateBooking
	(*APIKeyValidateResponse)(nil),                   // 2: api_key.APIKeyValidateResponse
	(*APIKeyValidateConsumeResponse)(nil),            // 3: api_key.APIKeyValidateConsumeResponse
	(*APIKeyValidateBookingResponse)(nil),            // 4: api_key.APIKeyValidateBookingResponse
	(*APIKeyValidateResponse_Successful)(nil),        // 5: api_key.APIKeyValidateResponse.Successful
	(*APIKeyValidateResponse_Failed)(nil),            // 6: api_key.APIKeyValidateResponse.Failed
	(*APIKeyValidateConsumeResponse_Successful)(nil), // 7: api_key.APIKeyValidateConsumeResponse.Successful
	(*APIKeyValidateConsumeResponse_Failed)(nil),     // 8: api_key.APIKeyValidateConsumeResponse.Failed
	(*APIKeyValidateBookingResponse_Successful)(nil), // 9: api_key.APIKeyValidateBookingResponse.Successful
	(*APIKeyValidateBookingResponse_Failed)(nil),     // 10: api_key.APIKeyValidateBookingResponse.Failed
	(*timestamp.Timestamp)(nil),                      // 11: google.protobuf.Timestamp
}
var file_internal_adapters_grpc_api_key_proto_api_key_proto_depIdxs = []int32{
	11, // 0: api_key.APIKeyValidate.request_time:type_name -> google.protobuf.Timestamp
	5,  // 1: api_key.APIKeyValidateResponse.successful:type_name -> api_key.APIKeyValidateResponse.Successful
	6,  // 2: api_key.APIKeyValidateResponse.failed:type_name -> api_key.APIKeyValidateResponse.Failed
	7,  // 3: api_key.APIKeyValidateConsumeResponse.successful:type_name -> api_key.APIKeyValidateConsumeResponse.Successful
	8,  // 4: api_key.APIKeyValidateConsumeResponse.failed:type_name -> api_key.APIKeyValidateConsumeResponse.Failed
	9,  // 5: api_key.APIKeyValidateBookingResponse.successful:type_name -> api_key.APIKeyValidateBookingResponse.Successful
	10, // 6: api_key.APIKeyValidateBookingResponse.failed:type_name -> api_key.APIKeyValidateBookingResponse.Failed
	1,  // 7: api_key.APIKeyService.Validate:input_type -> api_key.APIKeyValidateBooking
	0,  // 8: api_key.APIKeyService.ValidateAndConsume:input_type -> api_key.APIKeyValidate
	0,  // 9: api_key.APIKeyService.ValidateAndBooking:input_type -> api_key.APIKeyValidate
	2,  // 10: api_key.APIKeyService.Validate:output_type -> api_key.APIKeyValidateResponse
	3,  // 11: api_key.APIKeyService.ValidateAndConsume:output_type -> api_key.APIKeyValidateConsumeResponse
	4,  // 12: api_key.APIKeyService.ValidateAndBooking:output_type -> api_key.APIKeyValidateBookingResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_internal_adapters_grpc_api_key_proto_api_key_proto_init() }
func file_internal_adapters_grpc_api_key_proto_api_key_proto_init() {
	if File_internal_adapters_grpc_api_key_proto_api_key_proto != nil {
		return
	}
	file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[2].OneofWrappers = []any{
		(*APIKeyValidateResponse_Successful_)(nil),
		(*APIKeyValidateResponse_Failed_)(nil),
	}
	file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[3].OneofWrappers = []any{
		(*APIKeyValidateConsumeResponse_Successful_)(nil),
		(*APIKeyValidateConsumeResponse_Failed_)(nil),
	}
	file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes[4].OneofWrappers = []any{
		(*APIKeyValidateBookingResponse_Successful_)(nil),
		(*APIKeyValidateBookingResponse_Failed_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDesc), len(file_internal_adapters_grpc_api_key_proto_api_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_adapters_grpc_api_key_proto_api_key_proto_goTypes,
		DependencyIndexes: file_internal_adapters_grpc_api_key_proto_api_key_proto_depIdxs,
		MessageInfos:      file_internal_adapters_grpc_api_key_proto_api_key_proto_msgTypes,
	}.Build()
	File_internal_adapters_grpc_api_key_proto_api_key_proto = out.File
	file_internal_adapters_grpc_api_key_proto_api_key_proto_goTypes = nil
	file_internal_adapters_grpc_api_key_proto_api_key_proto_depIdxs = nil
}
