version: "3.8"

services:
  pandora-core:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    container_name: pandora-core-dev
    volumes:
      - ..:/app
    ports:
      - "8080:80"
      - "50051:50051"
      - "2345:2345"
    environment:
      - PANDORA_DB_DNS=postgres://pandora:pandora@postgres:5432/pandora?sslmode=disable&timezone=UTC
      - PANDORA_JWT_SECRET=your_jwt_secret
      - PANDORA_EXPOSE_VERSION=true
    depends_on:
      - postgres
    networks:
      - pandora-net

  postgres:
    image: pandora-postgres
    build:
      context: ../db
      dockerfile: dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pandora
      - POSTGRES_PASSWORD=pandora
      - POSTGRES_DB=pandora
    networks:
      - pandora-net

networks:
  pandora-net:
    driver: bridge
