// Code generated by MockGen. DO NOT EDIT.
// Source: internal/validator/validators.go
//
// Generated by this command:
//
//	mockgen -source=internal/validator/validators.go -destination=internal/validator/mock/validators.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	errors "github.com/MAD-py/pandora-core/internal/domain/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
	isgomock struct{}
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// ValidateStruct mocks base method.
func (m *MockValidator) ValidateStruct(value any, messages map[string]string) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateStruct", value, messages)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// ValidateStruct indicates an expected call of ValidateStruct.
func (mr *MockValidatorMockRecorder) ValidateStruct(value, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateStruct", reflect.TypeOf((*MockValidator)(nil).ValidateStruct), value, messages)
}

// ValidateVariable mocks base method.
func (m *MockValidator) ValidateVariable(value any, fieldName, tags string, messages map[string]string) errors.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateVariable", value, fieldName, tags, messages)
	ret0, _ := ret[0].(errors.Error)
	return ret0
}

// ValidateVariable indicates an expected call of ValidateVariable.
func (mr *MockValidatorMockRecorder) ValidateVariable(value, fieldName, tags, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateVariable", reflect.TypeOf((*MockValidator)(nil).ValidateVariable), value, fieldName, tags, messages)
}
