// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: request/v1/request.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestExecutionStatus int32

const (
	RequestExecutionStatus_REQUEST_EXECUTION_STATUS_NULL         RequestExecutionStatus = 0
	RequestExecutionStatus_REQUEST_EXECUTION_STATUS_SUCCESS      RequestExecutionStatus = 1
	RequestExecutionStatus_REQUEST_EXECUTION_STATUS_FAILED       RequestExecutionStatus = 2
	RequestExecutionStatus_REQUEST_EXECUTION_STATUS_PENDING      RequestExecutionStatus = 3
	RequestExecutionStatus_REQUEST_EXECUTION_STATUS_UNAUTHORIZED RequestExecutionStatus = 4
	RequestExecutionStatus_REQUEST_EXECUTION_STATUS_SERVER_ERROR RequestExecutionStatus = 5
)

// Enum value maps for RequestExecutionStatus.
var (
	RequestExecutionStatus_name = map[int32]string{
		0: "REQUEST_EXECUTION_STATUS_NULL",
		1: "REQUEST_EXECUTION_STATUS_SUCCESS",
		2: "REQUEST_EXECUTION_STATUS_FAILED",
		3: "REQUEST_EXECUTION_STATUS_PENDING",
		4: "REQUEST_EXECUTION_STATUS_UNAUTHORIZED",
		5: "REQUEST_EXECUTION_STATUS_SERVER_ERROR",
	}
	RequestExecutionStatus_value = map[string]int32{
		"REQUEST_EXECUTION_STATUS_NULL":         0,
		"REQUEST_EXECUTION_STATUS_SUCCESS":      1,
		"REQUEST_EXECUTION_STATUS_FAILED":       2,
		"REQUEST_EXECUTION_STATUS_PENDING":      3,
		"REQUEST_EXECUTION_STATUS_UNAUTHORIZED": 4,
		"REQUEST_EXECUTION_STATUS_SERVER_ERROR": 5,
	}
)

func (x RequestExecutionStatus) Enum() *RequestExecutionStatus {
	p := new(RequestExecutionStatus)
	*p = x
	return p
}

func (x RequestExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_request_v1_request_proto_enumTypes[0].Descriptor()
}

func (RequestExecutionStatus) Type() protoreflect.EnumType {
	return &file_request_v1_request_proto_enumTypes[0]
}

func (x RequestExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestExecutionStatus.Descriptor instead.
func (RequestExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_request_v1_request_proto_rawDescGZIP(), []int{0}
}

type SetRequestStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        RequestExecutionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=request.v1.RequestExecutionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequestStatusRequest) Reset() {
	*x = SetRequestStatusRequest{}
	mi := &file_request_v1_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequestStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequestStatusRequest) ProtoMessage() {}

func (x *SetRequestStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_v1_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequestStatusRequest.ProtoReflect.Descriptor instead.
func (*SetRequestStatusRequest) Descriptor() ([]byte, []int) {
	return file_request_v1_request_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequestStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetRequestStatusRequest) GetStatus() RequestExecutionStatus {
	if x != nil {
		return x.Status
	}
	return RequestExecutionStatus_REQUEST_EXECUTION_STATUS_NULL
}

var File_request_v1_request_proto protoreflect.FileDescriptor

const file_request_v1_request_proto_rawDesc = "" +
	"\n" +
	"\x18request/v1/request.proto\x12\n" +
	"request.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\"q\n" +
	"\x17SetRequestStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12F\n" +
	"\x06status\x18\x02 \x01(\x0e2\".request.v1.RequestExecutionStatusB\n" +
	"\xbaH\a\x82\x01\x04 \x00 \x04R\x06status*\x82\x02\n" +
	"\x16RequestExecutionStatus\x12!\n" +
	"\x1dREQUEST_EXECUTION_STATUS_NULL\x10\x00\x12$\n" +
	" REQUEST_EXECUTION_STATUS_SUCCESS\x10\x01\x12#\n" +
	"\x1fREQUEST_EXECUTION_STATUS_FAILED\x10\x02\x12$\n" +
	" REQUEST_EXECUTION_STATUS_PENDING\x10\x03\x12)\n" +
	"%REQUEST_EXECUTION_STATUS_UNAUTHORIZED\x10\x04\x12)\n" +
	"%REQUEST_EXECUTION_STATUS_SERVER_ERROR\x10\x052a\n" +
	"\x0eRequestService\x12O\n" +
	"\x10SetRequestStatus\x12#.request.v1.SetRequestStatusRequest\x1a\x16.google.protobuf.EmptyB\fZ\n" +
	"request/pbb\x06proto3"

var (
	file_request_v1_request_proto_rawDescOnce sync.Once
	file_request_v1_request_proto_rawDescData []byte
)

func file_request_v1_request_proto_rawDescGZIP() []byte {
	file_request_v1_request_proto_rawDescOnce.Do(func() {
		file_request_v1_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_v1_request_proto_rawDesc), len(file_request_v1_request_proto_rawDesc)))
	})
	return file_request_v1_request_proto_rawDescData
}

var file_request_v1_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_request_v1_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_v1_request_proto_goTypes = []any{
	(RequestExecutionStatus)(0),     // 0: request.v1.RequestExecutionStatus
	(*SetRequestStatusRequest)(nil), // 1: request.v1.SetRequestStatusRequest
	(*emptypb.Empty)(nil),           // 2: google.protobuf.Empty
}
var file_request_v1_request_proto_depIdxs = []int32{
	0, // 0: request.v1.SetRequestStatusRequest.status:type_name -> request.v1.RequestExecutionStatus
	1, // 1: request.v1.RequestService.SetRequestStatus:input_type -> request.v1.SetRequestStatusRequest
	2, // 2: request.v1.RequestService.SetRequestStatus:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_request_v1_request_proto_init() }
func file_request_v1_request_proto_init() {
	if File_request_v1_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_v1_request_proto_rawDesc), len(file_request_v1_request_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_request_v1_request_proto_goTypes,
		DependencyIndexes: file_request_v1_request_proto_depIdxs,
		EnumInfos:         file_request_v1_request_proto_enumTypes,
		MessageInfos:      file_request_v1_request_proto_msgTypes,
	}.Build()
	File_request_v1_request_proto = out.File
	file_request_v1_request_proto_goTypes = nil
	file_request_v1_request_proto_depIdxs = nil
}
