// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: api_key/v1/api_key.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Body            string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Headers         string                 `protobuf:"bytes,2,opt,name=headers,proto3" json:"headers,omitempty"`
	QueryParams     string                 `protobuf:"bytes,3,opt,name=query_params,json=queryParams,proto3" json:"query_params,omitempty"`
	BodyContentType string                 `protobuf:"bytes,4,opt,name=body_content_type,json=bodyContentType,proto3" json:"body_content_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestMetadata) Reset() {
	*x = RequestMetadata{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetadata) ProtoMessage() {}

func (x *RequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetadata.ProtoReflect.Descriptor instead.
func (*RequestMetadata) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMetadata) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *RequestMetadata) GetHeaders() string {
	if x != nil {
		return x.Headers
	}
	return ""
}

func (x *RequestMetadata) GetQueryParams() string {
	if x != nil {
		return x.QueryParams
	}
	return ""
}

func (x *RequestMetadata) GetBodyContentType() string {
	if x != nil {
		return x.BodyContentType
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Metadata      *RequestMetadata       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RequestTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Request) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Request) GetRequestTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestTime
	}
	return nil
}

type ValidateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApiKey         string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Request        *Request               `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	ServiceName    string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceVersion string                 `protobuf:"bytes,4,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ValidateRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ValidateRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ValidateRequest) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{3}
}

func (x *Project) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{4}
}

func (x *Client) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{5}
}

func (x *Environment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Environment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FailureCode   string                 `protobuf:"bytes,3,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	Project       *Project               `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	Client        *Client                `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Environment   *Environment           `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ValidateResponse) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

func (x *ValidateResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ValidateResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *ValidateResponse) GetEnvironment() *Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

type ValidateConsumeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse     *ValidateResponse      `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	AvailableRequest int64                  `protobuf:"varint,2,opt,name=available_request,json=availableRequest,proto3" json:"available_request,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateConsumeResponse) Reset() {
	*x = ValidateConsumeResponse{}
	mi := &file_api_key_v1_api_key_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConsumeResponse) ProtoMessage() {}

func (x *ValidateConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_v1_api_key_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConsumeResponse.ProtoReflect.Descriptor instead.
func (*ValidateConsumeResponse) Descriptor() ([]byte, []int) {
	return file_api_key_v1_api_key_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateConsumeResponse) GetBaseResponse() *ValidateResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *ValidateConsumeResponse) GetAvailableRequest() int64 {
	if x != nil {
		return x.AvailableRequest
	}
	return 0
}

var File_api_key_v1_api_key_proto protoreflect.FileDescriptor

const file_api_key_v1_api_key_proto_rawDesc = "" +
	"\n" +
	"\x18api_key/v1/api_key.proto\x12\n" +
	"api_key.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x02\n" +
	"\x0fRequestMetadata\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x12\x18\n" +
	"\aheaders\x18\x02 \x01(\tR\aheaders\x12!\n" +
	"\fquery_params\x18\x03 \x01(\tR\vqueryParams\x12\xc0\x01\n" +
	"\x11body_content_type\x18\x04 \x01(\tB\x93\x01\xbaH\x8f\x01r\x8c\x01R\x0fapplication/xmlR\x10application/jsonR\n" +
	"text/plainR\ttext/htmlR\x13multipart/form-dataR!application/x-www-form-urlencodedR\x18application/octet-streamR\x0fbodyContentType\"\x91\x02\n" +
	"\aRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12[\n" +
	"\x06method\x18\x02 \x01(\tBC\xbaH@r>R\x03GETR\x04HEADR\x04POSTR\x03PUTR\x05PATCHR\x06DELETER\aCONNECTR\aOPTIONSR\x05TRACER\x06method\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x127\n" +
	"\bmetadata\x18\x04 \x01(\v2\x1b.api_key.v1.RequestMetadataR\bmetadata\x12=\n" +
	"\frequest_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestTime\"\xa5\x01\n" +
	"\x0fValidateRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12-\n" +
	"\arequest\x18\x02 \x01(\v2\x13.api_key.v1.RequestR\arequest\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_version\x18\x04 \x01(\tR\x0eserviceVersion\"-\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\",\n" +
	"\x06Client\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"1\n" +
	"\vEnvironment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb3\x03\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\xd3\x01\n" +
	"\ffailure_code\x18\x03 \x01(\tB\xaf\x01\xbaH\xab\x01r\xa8\x01R\x0fAPI_KEY_INVALIDR\x0eQUOTA_EXCEEDEDR\x0fAPI_KEY_EXPIREDR\x10API_KEY_DISABLEDR\x10SERVICE_MISMATCHR\x10SERVICE_DISABLEDR\x12SERVICE_DEPRECATEDR\x14SERVICE_NOT_ASSIGNEDR\x14ENVIRONMENT_DISABLEDR\vfailureCode\x12-\n" +
	"\aproject\x18\x04 \x01(\v2\x13.api_key.v1.ProjectR\aproject\x12*\n" +
	"\x06client\x18\x05 \x01(\v2\x12.api_key.v1.ClientR\x06client\x129\n" +
	"\venvironment\x18\x06 \x01(\v2\x17.api_key.v1.EnvironmentR\venvironment\"\x89\x01\n" +
	"\x17ValidateConsumeResponse\x12A\n" +
	"\rbase_response\x18\x01 \x01(\v2\x1c.api_key.v1.ValidateResponseR\fbaseResponse\x12+\n" +
	"\x11available_request\x18\x02 \x01(\x03R\x10availableRequest2\xab\x01\n" +
	"\rAPIKeyService\x12E\n" +
	"\bValidate\x12\x1b.api_key.v1.ValidateRequest\x1a\x1c.api_key.v1.ValidateResponse\x12S\n" +
	"\x0fValidateConsume\x12\x1b.api_key.v1.ValidateRequest\x1a#.api_key.v1.ValidateConsumeResponseB\fZ\n" +
	"api_key/pbb\x06proto3"

var (
	file_api_key_v1_api_key_proto_rawDescOnce sync.Once
	file_api_key_v1_api_key_proto_rawDescData []byte
)

func file_api_key_v1_api_key_proto_rawDescGZIP() []byte {
	file_api_key_v1_api_key_proto_rawDescOnce.Do(func() {
		file_api_key_v1_api_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_key_v1_api_key_proto_rawDesc), len(file_api_key_v1_api_key_proto_rawDesc)))
	})
	return file_api_key_v1_api_key_proto_rawDescData
}

var file_api_key_v1_api_key_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_key_v1_api_key_proto_goTypes = []any{
	(*RequestMetadata)(nil),         // 0: api_key.v1.RequestMetadata
	(*Request)(nil),                 // 1: api_key.v1.Request
	(*ValidateRequest)(nil),         // 2: api_key.v1.ValidateRequest
	(*Project)(nil),                 // 3: api_key.v1.Project
	(*Client)(nil),                  // 4: api_key.v1.Client
	(*Environment)(nil),             // 5: api_key.v1.Environment
	(*ValidateResponse)(nil),        // 6: api_key.v1.ValidateResponse
	(*ValidateConsumeResponse)(nil), // 7: api_key.v1.ValidateConsumeResponse
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
}
var file_api_key_v1_api_key_proto_depIdxs = []int32{
	0, // 0: api_key.v1.Request.metadata:type_name -> api_key.v1.RequestMetadata
	8, // 1: api_key.v1.Request.request_time:type_name -> google.protobuf.Timestamp
	1, // 2: api_key.v1.ValidateRequest.request:type_name -> api_key.v1.Request
	3, // 3: api_key.v1.ValidateResponse.project:type_name -> api_key.v1.Project
	4, // 4: api_key.v1.ValidateResponse.client:type_name -> api_key.v1.Client
	5, // 5: api_key.v1.ValidateResponse.environment:type_name -> api_key.v1.Environment
	6, // 6: api_key.v1.ValidateConsumeResponse.base_response:type_name -> api_key.v1.ValidateResponse
	2, // 7: api_key.v1.APIKeyService.Validate:input_type -> api_key.v1.ValidateRequest
	2, // 8: api_key.v1.APIKeyService.ValidateConsume:input_type -> api_key.v1.ValidateRequest
	6, // 9: api_key.v1.APIKeyService.Validate:output_type -> api_key.v1.ValidateResponse
	7, // 10: api_key.v1.APIKeyService.ValidateConsume:output_type -> api_key.v1.ValidateConsumeResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_key_v1_api_key_proto_init() }
func file_api_key_v1_api_key_proto_init() {
	if File_api_key_v1_api_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_key_v1_api_key_proto_rawDesc), len(file_api_key_v1_api_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_key_v1_api_key_proto_goTypes,
		DependencyIndexes: file_api_key_v1_api_key_proto_depIdxs,
		MessageInfos:      file_api_key_v1_api_key_proto_msgTypes,
	}.Build()
	File_api_key_v1_api_key_proto = out.File
	file_api_key_v1_api_key_proto_goTypes = nil
	file_api_key_v1_api_key_proto_depIdxs = nil
}
