// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: request/v1/request.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateExecutionStatusRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Detail          string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	StatusCode      int64                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ExecutionStatus string                 `protobuf:"bytes,4,opt,name=execution_status,json=executionStatus,proto3" json:"execution_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateExecutionStatusRequest) Reset() {
	*x = UpdateExecutionStatusRequest{}
	mi := &file_request_v1_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExecutionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExecutionStatusRequest) ProtoMessage() {}

func (x *UpdateExecutionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_v1_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExecutionStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateExecutionStatusRequest) Descriptor() ([]byte, []int) {
	return file_request_v1_request_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateExecutionStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateExecutionStatusRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *UpdateExecutionStatusRequest) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateExecutionStatusRequest) GetExecutionStatus() string {
	if x != nil {
		return x.ExecutionStatus
	}
	return ""
}

var File_request_v1_request_proto protoreflect.FileDescriptor

const file_request_v1_request_proto_rawDesc = "" +
	"\n" +
	"\x18request/v1/request.proto\x12\n" +
	"request.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xbe\x01\n" +
	"\x1cUpdateExecutionStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x03R\n" +
	"statusCode\x12U\n" +
	"\x10execution_status\x18\x04 \x01(\tB*\xbaH'r%R\asuccessR\fclient_errorR\fserver_errorR\x0fexecutionStatus2k\n" +
	"\x0eRequestService\x12Y\n" +
	"\x15UpdateExecutionStatus\x12(.request.v1.UpdateExecutionStatusRequest\x1a\x16.google.protobuf.EmptyB\fZ\n" +
	"request/pbb\x06proto3"

var (
	file_request_v1_request_proto_rawDescOnce sync.Once
	file_request_v1_request_proto_rawDescData []byte
)

func file_request_v1_request_proto_rawDescGZIP() []byte {
	file_request_v1_request_proto_rawDescOnce.Do(func() {
		file_request_v1_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_v1_request_proto_rawDesc), len(file_request_v1_request_proto_rawDesc)))
	})
	return file_request_v1_request_proto_rawDescData
}

var file_request_v1_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_v1_request_proto_goTypes = []any{
	(*UpdateExecutionStatusRequest)(nil), // 0: request.v1.UpdateExecutionStatusRequest
	(*emptypb.Empty)(nil),                // 1: google.protobuf.Empty
}
var file_request_v1_request_proto_depIdxs = []int32{
	0, // 0: request.v1.RequestService.UpdateExecutionStatus:input_type -> request.v1.UpdateExecutionStatusRequest
	1, // 1: request.v1.RequestService.UpdateExecutionStatus:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_v1_request_proto_init() }
func file_request_v1_request_proto_init() {
	if File_request_v1_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_v1_request_proto_rawDesc), len(file_request_v1_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_request_v1_request_proto_goTypes,
		DependencyIndexes: file_request_v1_request_proto_depIdxs,
		MessageInfos:      file_request_v1_request_proto_msgTypes,
	}.Build()
	File_request_v1_request_proto = out.File
	file_request_v1_request_proto_goTypes = nil
	file_request_v1_request_proto_depIdxs = nil
}
