// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/auth/reauthenticate/ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/auth/reauthenticate/ports.go -destination=internal/app/auth/reauthenticate/mock/ports.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/MAD-py/pandora-core/internal/domain/dto"
	entities "github.com/MAD-py/pandora-core/internal/domain/entities"
	errors "github.com/MAD-py/pandora-core/internal/domain/errors"
	gomock "go.uber.org/mock/gomock"
)

// MockCredentialsRepository is a mock of CredentialsRepository interface.
type MockCredentialsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialsRepositoryMockRecorder
	isgomock struct{}
}

// MockCredentialsRepositoryMockRecorder is the mock recorder for MockCredentialsRepository.
type MockCredentialsRepositoryMockRecorder struct {
	mock *MockCredentialsRepository
}

// NewMockCredentialsRepository creates a new mock instance.
func NewMockCredentialsRepository(ctrl *gomock.Controller) *MockCredentialsRepository {
	mock := &MockCredentialsRepository{ctrl: ctrl}
	mock.recorder = &MockCredentialsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialsRepository) EXPECT() *MockCredentialsRepositoryMockRecorder {
	return m.recorder
}

// GetByUsername mocks base method.
func (m *MockCredentialsRepository) GetByUsername(ctx context.Context, username string) (*entities.Credentials, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(*entities.Credentials)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockCredentialsRepositoryMockRecorder) GetByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockCredentialsRepository)(nil).GetByUsername), ctx, username)
}

// MockTokenProvider is a mock of TokenProvider interface.
type MockTokenProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTokenProviderMockRecorder
	isgomock struct{}
}

// MockTokenProviderMockRecorder is the mock recorder for MockTokenProvider.
type MockTokenProviderMockRecorder struct {
	mock *MockTokenProvider
}

// NewMockTokenProvider creates a new mock instance.
func NewMockTokenProvider(ctrl *gomock.Controller) *MockTokenProvider {
	mock := &MockTokenProvider{ctrl: ctrl}
	mock.recorder = &MockTokenProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenProvider) EXPECT() *MockTokenProviderMockRecorder {
	return m.recorder
}

// ValidateScopedToken mocks base method.
func (m *MockTokenProvider) ValidateScopedToken(ctx context.Context, subject, scope string) (*dto.TokenResponse, errors.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateScopedToken", ctx, subject, scope)
	ret0, _ := ret[0].(*dto.TokenResponse)
	ret1, _ := ret[1].(errors.Error)
	return ret0, ret1
}

// ValidateScopedToken indicates an expected call of ValidateScopedToken.
func (mr *MockTokenProviderMockRecorder) ValidateScopedToken(ctx, subject, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateScopedToken", reflect.TypeOf((*MockTokenProvider)(nil).ValidateScopedToken), ctx, subject, scope)
}
