name: Code Scanning with Vet & Staticcheck

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  scan:
    name: Analyze Go Code Quality
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Extract Go version from go.mod
        id: go-version
        run: echo "version=$(grep '^go ' go.mod | awk '{print $2}')" >> "$GITHUB_OUTPUT"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.go-version.outputs.version }}

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          echo "${GOPATH}/bin" >> $GITHUB_PATH

      - name: Run staticcheck
        run: staticcheck ./...
